name: Deploy Amazon Machine Image (AMI) to AWS

on:
  push:
    branches:
      - main  # deploy only on master branch

# env:
#   # Setting an environment variable with the value of a configuration variable
#   env_var: ${{ vars.ENV_CONTEXT_VAR }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
          
      # Step 3: Build CentOS Base AMI from CentOS Stream 
      - name: Build CentOS Base AMI from CentOS Stream
        run: |
          packer init ./centos
          packer build ./centos


      # Step 3: Build ServiceNow Base from CentOS AMI
      - name: Build ServiceNow Base from CentOS AMI
        run: |
          packer init ./servicenow
          packer build -var-file=./servicenow/variables.pkrvars.hcl ./servicenow

          

